//! Agent Generator — Stage 0 of E2E Sovereign Pipeline
//! Takes short natural-language prompt and produces minimal MeaningSeed file set
//! + runs initial polarity check.

use std::fs;
use std::path::Path;

#[derive(Debug)]
pub struct MeaningSeedStub {
    pub name: String,
    pub version: String,
    pub description: String,
}

pub fn generate_meaningseed_stub(prompt: &str) -> MeaningSeedStub {
    // Very simple heuristic extraction for prototype
    let name = prompt.split_whitespace().take(3).collect::<Vec<_>>().join("_");
    MeaningSeedStub {
        name: if name.is_empty() { "default_meaningseed".to_string() } else { name },
        version: "2026.06.,28-v0.1".to_string(),
        description: prompt.to_string(),
    }
}

pub fn write_meaningseed_files(stub: &MeaningSeedStub, output_dir: &Path) -> std::io::Result<()> {
    fs::create_dir_all(output_dir)?;

    let toml_content = format!(
        r#"[seed]
name = "{}"
version = "{}"
type = "MeaningSeed Deployment Artifact"
description = "{}"
source = "TriWeavon Agent Generator (Stage 0)"

[pre-flight]
checks = ["python_version", "dependencies", "dynamics_import"]
verification_command = "bash bin/preflight.sh"
"#,
        stub.name, stub.version, stub.description
    );

    fs::write(output_dir.join("meaningseed.toml"), toml_content)?;

    // Minimal stub files
    fs::write(output_dir.join("src/lib.rs"), "// Minimal MeaningSeed stub generated by Agent Generator\n")?;
    fs::write(output_dir.join("formal/TriWeavon.agda"), "-- Minimal Agda header generated by Agent Generator\n")?;

    Ok(())
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 2 {
        eprintln!("Usage: agent-generator \"<short prompt>\"");
        std::process::exit(1);
    }

    let prompt = &args[1];
    let stub = generate_meaningseed_stub(prompt);
    let output_dir = Path::new("generated_meaningseed");

    match write_meaningseed_files(&stub, output_dir) {
        Ok(_) => {
            println!("MeaningSeed generated at {:?}", output_dir);
            println!("Initial polarity check: ALIGNED (stub)");
        }
        Err(e) => {
            eprintln!("Error writing files: {}", e);
            std::process::exit(1);
        }
    }
}
